<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to block this comment?' => 'Вы уверены что хотите заблокировать этот отзыв?',
    'Are you sure you want to unblock this comment?' => 'Вы уверены что хотите разблокировать этот отзыв?',
    'Block' => 'Заблокировать',
    'Content' => 'Контент',
    'Create comment' => 'Создать отзыв',
    'Created at' => 'Создано в',
    'Edit comment #{id}' => 'Редактировать отзыв #{id}',
    'From' => 'От',
    'List' => 'Список',
    'New comment' => 'Новый отзыв',
    'Reply' => 'Комментировать',
    'Reply to:' => 'Ответ на:',
    'Reset filter' => 'Сбросить фильтр',
    'Save' => 'Сохранить',
    'Select user' => 'Выберите пользователя',
    'The requested comment does not exist' => 'Запрошенный отзыв не существует',
    'Unblock' => 'Разблокировать',
    'Comments' => 'Отзывы',
    'Website comments' => 'Отзывы к сайту',
    'Is blocked' => 'Заблокировано',
    'Send' => 'Отправить'
];
